add logo, its in static/textures/logo.png
change name to aegismesh and add logo to side
dont display name twice, i.e once in header but in sidebar also. Only in header, name the sidebar something else
Make sidebar collapsable
Add a fancy surrounding to connected
task details: instead of mlp write its full name
for privacy, add levels to it i.e. 1 being lowest (plaintext), then she, shedp, fhe, fhedp in order
reduce height of global perf chart tab a little
reduce height of globe controls
center align the live metric and reduce height of this tab,
make Aggregation & Economics tab into Token Economy, remove tps, centerc align the heading of this tab and its info too. add scrolling to that tab
model marketplace tabs have buggy height, they reach the end of the page. maker it fixed shorter.
improve ui of amount to stake field

change all mentions of server in frontewnd to Aggregator / aggregation center

Have
Auto-Rotate
Show Clouds
switched on by default, dont save its state, its buggy

change name of all clients so far, 0 - 20 to the names of popular research centers/colleges, and their locations.

keep Bhopal intact/untouched
